### ISSUE TITLE
Problème slider

### ISSUE THREAD

**Issue by BetaPeche** [lesimpleliott/Katelio-Wedding-Photos#1]
Si je vais dans un album,
que j'ouvre une photo,
que je reviens en arrière en appuyant sur le bouton 'retour' de mon navigateur et que je vais dans un autre album, j'ai le slider qui s'ouvre avec la photo que j'avais ouvert dans l'album précédent.

**Comment by lesimpleliott** [comment]
Debug : Okk 
Solution : reset du slider avec closeSlider sur Home
